# Generated by Django 4.1 on 2022-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="point", name="onoff",),
        migrations.AddField(
            model_name="time_settings",
            name="onoff",
            field=models.BooleanField(default=True),
        ),
    ]
